name: netflex_timeline
description: A timetable/multitimeline library
version: 1.0.0
repository: https://github.com/tommysolsen/netflex_timeline

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
